### ISSUE TITLE
logout action throws exception due to "status-code: 1000"

### ISSUE THREAD

**Issue by mbunkus** [kolodovskyy/joker-dmapi#1]
First of all thanks a lot for this gem. I use it and am quite happy with it.

I don't know since when, but the logout action throws an exception (IDs cut off by me):

```text
status_code: 1000
status_text: OK
svtrid: 01d30…
tracking_id: 01d30…
timing: 0.001976/0.005268 37.504%

Session destroyed

```

Running with debug output shows the following (IDs again cut off by me):

```text
>> https://dmapi.joker.com:443/request/logout?auth-sid=469941…
<< Status-Code: 1000
<< Status-Text: OK
<< SvTrId: 01d30…
<< Tracking-Id: 01d30…
<< Timing: 0.002247/0.006321 35.548%
<<
<< Session destroyed
```

A backtrace shows that this happens in `JokerDMAPI::Client::query` and is due to the following line:

```ruby
      raise_response(response) unless response[:headers][:status_code] == '0'
```

I've monkey-patched this not to fail for `:status_code == '1000'` and `:status_text == 'OK'`. Don't know if that's the right thing to do.

**Comment by kolodovskyi** [comment]
Yes, Joker changed status-code for logout about half a year ago. I do not know why.
Actual documentation https://dmapi.joker.com/docs/DMAPI-ext.txt

> Status-Code: Not 0 if error occurred

But logout action is

> Normally not required as session will timeout eventually (default after 1 hour)

So, when status-code was changed I just removed logout action from my code :)
I will fix `JokerDMAPI::Client::query` a little later.
