### ISSUE TITLE
depends on addressable 0.x which uses deprecated constants

### ISSUE THREAD

**Issue by mbunkus** [kolodovskyy/joker-dmapi#3]
The `joker-dmapi` gem 0.1.5 currently has the following dependency:

`joker-dmapi-0.1.5 depends on addressable (~> 0)`

The problem with `addressable` 0.1.2, the latest 0.x version available, is that it uses constants deprecated in current Ruby versions:

```
/opt/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/addressable-0.1.2/lib/addressable/uri.rb:462: warning: constant ::Fixnum is deprecated
```

There are various 1.y and 2.z releases. I accidentally used my local git clone of `joker-dmapi` with `addressable` latest release, 2.5.2, without having `addressable` 0.1.2 installed, and that worked fine as far as I can tell.

Please update the gem's dependency to a higher version of `addressable`. I don't know anything about how gem dependencies work (the `.gemspec` file doesn't mention versions explicitly); otherwise I'd create a PR for that.

Thanks.

**Comment by mbunkus** [comment]
Oh, I just saw that you explicitly added the `~> 0` requirement in 39f6cb6bd7c356c4d97ea7fc9d42aca374a6c347. This means, if I'm not mistaken, "any minor version with major version == 0". Is there a particular reason you require major 0?

This breaks my scripts, BTW, which also use the `dnsruby` gem which in turn depends on `addressable >= 2.5` — and loading two different versions of the same gem in the same program doesn't work.

**Comment by kolodovskyi** [comment]
It was my mistake.
gemspec reverted, version removed
gem updated

please, try it

**Comment by mbunkus** [comment]
Thanks. I've just gone home & will test tomorrow at work.

**Comment by mbunkus** [comment]
Your updated 0.1.6 works nicely with only `addressable` 2.5.2 installed. Thank you very much.
